export function initMocks() {
  const regrasMock = [
    {
      id: '1a2b3c4d-0001',
      nome: 'Falha de Login',
      descricao: 'Monitora falhas consecutivas de login de usuários',
      sql: "SELECT count(*) FROM logins WHERE success = false AND timestamp > NOW() - INTERVAL '5 minutes'",
      banco: 'PostgreSQL',
      prioridade: 'Alta',
      minuto_atualizacao: 1,
      qtd_erro_max: 5,
      timeout: 30,
      hora_inicio: '00:00',
      hora_final: '23:59',
      roles: 'INFRA',
      notificacao: true,
      silenciar: false,
      executar: true,
      data_adiar: null
    },
    {
      id: '1a2b3c4d-0002',
      nome: 'Banco Offline',
      descricao: 'Verifica se o banco de dados está respondendo',
      sql: 'SELECT 1',
      banco: 'PostgreSQL',
      prioridade: 'Alta',
      minuto_atualizacao: 2,
      qtd_erro_max: 3,
      timeout: 20,
      hora_inicio: '00:00',
      hora_final: '23:59',
      roles: 'INFRA',
      notificacao: true,
      silenciar: false,
      executar: true,
      data_adiar: '2025-12-25'
    },
    {
      id: '1a2b3c4d-0003',
      nome: 'API Lenta',
      descricao: 'Tempo de resposta da API acima de 5 segundos',
      sql: 'SELECT response_time FROM api_monitor WHERE response_time > 5000',
      banco: 'PostgreSQL',
      prioridade: 'Média',
      minuto_atualizacao: 5,
      qtd_erro_max: 2,
      timeout: 10,
      hora_inicio: '06:00',
      hora_final: '22:00',
      roles: 'CANAIS_DIGITAIS',
      notificacao: true,
      silenciar: false,
      executar: false,
      data_adiar: null
    },
    {
      id: '1a2b3c4d-0004',
      nome: 'Serviço de Email',
      descricao: 'Erro ao enviar emails para clientes',
      sql: "SELECT count(*) FROM emails WHERE status='failed' AND timestamp > NOW() - INTERVAL '10 minutes'",
      banco: 'PostgreSQL',
      prioridade: 'Média',
      minuto_atualizacao: 3,
      qtd_erro_max: 5,
      timeout: 15,
      hora_inicio: '07:00',
      hora_final: '21:00',
      roles: 'CANAIS_DIGITAIS',
      notificacao: true,
      silenciar: false,
      executar: true,
      data_adiar: '2025-12-05'
    },
    {
      id: '1a2b3c4d-0005',
      nome: 'CPU Alta',
      descricao: 'Monitoramento de uso da CPU acima de 90%',
      sql: 'SELECT cpu_usage FROM system_metrics WHERE cpu_usage > 90',
      banco: 'PostgreSQL',
      prioridade: 'Média',
      minuto_atualizacao: 1,
      qtd_erro_max: 3,
      timeout: 60,
      hora_inicio: '00:00',
      hora_final: '23:59',
      roles: 'INFRA',
      notificacao: true,
      silenciar: true,
      executar: false,
      data_adiar: null
    },
    {
      id: '1a2b3c4d-0006',
      nome: 'Memória Alta',
      descricao: 'Uso de memória acima de 80%',
      sql: 'SELECT memory_usage FROM system_metrics WHERE memory_usage > 80',
      banco: 'Oracle',
      prioridade: 'Alta',
      minuto_atualizacao: 2,
      qtd_erro_max: 4,
      timeout: 45,
      hora_inicio: '00:00',
      hora_final: '23:59',
      roles: 'INFRA',
      notificacao: true,
      silenciar: false,
      executar: true,
      data_adiar: null
    },
    {
      id: '1a2b3c4d-0007',
      nome: 'Erro Pagamento',
      descricao: 'Falhas em transações financeiras',
      sql: "SELECT count(*) FROM pagamentos WHERE status='falha' AND timestamp > NOW() - INTERVAL '15 minutes'",
      banco: 'PostgreSQL',
      prioridade: 'Alta',
      minuto_atualizacao: 5,
      qtd_erro_max: 2,
      timeout: 30,
      hora_inicio: '08:00',
      hora_final: '20:00',
      roles: 'FINANCEIRO',
      notificacao: true,
      silenciar: false,
      executar: true,
      data_adiar: '2025-12-31'
    },
    {
      id: '1a2b3c4d-0008',
      nome: 'Serviço Web Offline',
      descricao: 'Verifica se o serviço web está disponível',
      sql: 'SELECT status FROM web_services WHERE status != "online"',
      banco: 'PostgreSQL',
      prioridade: 'Alta',
      minuto_atualizacao: 1,
      qtd_erro_max: 1,
      timeout: 20,
      hora_inicio: '00:00',
      hora_final: '23:59',
      roles: 'CANAIS_DIGITAIS',
      notificacao: true,
      silenciar: false,
      executar: true,
      data_adiar: null
    },
    {
      id: '1a2b3c4d-0009',
      nome: 'Falha Backup',
      descricao: 'Falhas no backup do banco de dados',
      sql: 'SELECT count(*) FROM backups WHERE status="failed" AND timestamp > NOW() - INTERVAL "1 day"',
      banco: 'PostgreSQL',
      prioridade: 'Alta',
      minuto_atualizacao: 60,
      qtd_erro_max: 1,
      timeout: 120,
      hora_inicio: '01:00',
      hora_final: '05:00',
      roles: 'INFRA',
      notificacao: true,
      silenciar: false,
      executar: true,
      data_adiar: null
    },
    {
      id: '1a2b3c4d-0010',
      nome: 'Cache Expirado',
      descricao: 'Itens do cache expirados há mais de 10 minutos',
      sql: 'SELECT count(*) FROM cache WHERE last_update < NOW() - INTERVAL "10 minutes"',
      banco: 'Oracle',
      prioridade: 'Média',
      minuto_atualizacao: 5,
      qtd_erro_max: 3,
      timeout: 10,
      hora_inicio: '06:00',
      hora_final: '22:00',
      roles: 'CANAIS_DIGITAIS',
      notificacao: true,
      silenciar: true,
      executar: true,
      data_adiar: null
    }
  ]

  const incidentesMock = [
    {
      id: 'inc-0001',
      user_escalado: 'xFqKTC9mMUMxJtuJM3dVtsMV9SY2',
      regra_id: '1a2b3c4d-0001',
      user_id_ack: '',
      user_id_closed: '',
      status: 'open',
      comentario_ack: '',
      comentario_closed: '',
      created_at: '2025-10-23 09:15',
      ack_at: '',
      closed_at: '',
      logs: [
        { id: 'log-0001', incidente_id: 'inc-0001', time: '2025-10-23 09:15', message: 'Incidente criado' }
      ],
    },
    {
      id: 'inc-0002',
      user_escalado: 'fbMaxkasRefAgVxeSuxeTJIF5AS2',
      regra_id: '1a2b3c4d-0002',
      user_id_ack: 'xFqKTC9mMUMxJtuJM3dVtsMV9SY2',
      user_id_closed: '',
      status: 'ack',
      comentario_ack: 'Equipe de infraestrutura informada',
      comentario_closed: '',
      created_at: '2025-10-23 08:45',
      ack_at: '2025-10-23 08:50',
      closed_at: '',
      logs: [
        { id: 'log-0002', incidente_id: 'inc-0002', time: '2025-10-23 08:45', message: 'Incidente criado' },
        { id: 'log-0003', incidente_id: 'inc-0002', time: '2025-10-23 08:50', message: 'Incidente reconhecido' }
      ],
    },
    {
      id: 'inc-0003',
      user_escalado: 'mniYEzNopmPB08XkK5jDuTeANro1',
      regra_id: '1a2b3c4d-0003',
      user_id_ack: 'fbMaxkasRefAgVxeSuxeTJIF5AS2',
      user_id_closed: 'xFqKTC9mMUMxJtuJM3dVtsMV9SY2',
      status: 'closed',
      comentario_ack: 'Problema resolvido após ajuste no servidor',
      comentario_closed: 'Problema resolvido após ajuste no servidor',
      created_at: '2025-10-22 16:20',
      ack_at: '2025-10-22 16:25',
      closed_at: '2025-10-22 17:00',
      logs: [
        { id: 'log-0004', incidente_id: 'inc-0003', time: '2025-10-22 16:20', message: 'Incidente criado' },
        { id: 'log-0005', incidente_id: 'inc-0003', time: '2025-10-22 16:25', message: 'Incidente reconhecido' },
        { id: 'log-0006', incidente_id: 'inc-0003', time: '2025-10-22 17:00', message: 'Incidente fechado' }
      ],
    },
    {
      id: 'inc-0004',
      user_escalado: 'xFqKTC9mMUMxJtuJM3dVtsMV9SY2',
      regra_id: '1a2b3c4d-0004',
      user_id_ack: '',
      user_id_closed: '',
      status: 'open',
      comentario_ack: '',
      comentario_closed: '',
      created_at: '2025-10-23 10:00',
      ack_at: '',
      closed_at: '',
      logs: [
        { id: 'log-0007', incidente_id: 'inc-0004', time: '2025-10-23 10:00', message: 'Incidente criado' }
      ],
    },
    {
      id: 'inc-0005',
      user_escalado: 'mniYEzNopmPB08XkK5jDuTeANro1',
      regra_id: '1a2b3c4d-0005',
      user_id_ack: 'xFqKTC9mMUMxJtuJM3dVtsMV9SY2',
      user_id_closed: '',
      status: 'ack',
      comentario_ack: 'Verificar processos ativos',
      comentario_closed: '',
      created_at: '2025-10-23 07:30',
      ack_at: '2025-10-23 07:35',
      closed_at: '',
      logs: [
        { id: 'log-0008', incidente_id: 'inc-0005', time: '2025-10-23 07:30', message: 'Incidente criado' },
        { id: 'log-0009', incidente_id: 'inc-0005', time: '2025-10-23 07:35', message: 'Incidente reconhecido' }
      ],
    },
    {
      id: 'inc-0006',
      user_escalado: 'fbMaxkasRefAgVxeSuxeTJIF5AS2',
      regra_id: '1a2b3c4d-0006',
      user_id_ack: '',
      user_id_closed: '',
      status: 'open',
      comentario_ack: '',
      comentario_closed: '',
      created_at: '2025-10-23 10:30',
      ack_at: '',
      closed_at: '',
      logs: [
        { id: 'log-0010', incidente_id: 'inc-0006', time: '2025-10-23 10:30', message: 'Incidente criado' }
      ],
    },
    {
      id: 'inc-0007',
      user_escalado: 'xFqKTC9mMUMxJtuJM3dVtsMV9SY2',
      regra_id: '1a2b3c4d-0007',
      user_id_ack: '',
      user_id_closed: '',
      status: 'open',
      comentario_ack: '',
      comentario_closed: '',
      created_at: '2025-10-23 11:00',
      ack_at: '',
      closed_at: '',
      logs: [
        { id: 'log-0011', incidente_id: 'inc-0007', time: '2025-10-23 11:00', message: 'Incidente criado' }
      ],
    },
    {
      id: 'inc-0008',
      user_escalado: 'mniYEzNopmPB08XkK5jDuTeANro1',
      regra_id: '1a2b3c4d-0008',
      user_id_ack: 'xFqKTC9mMUMxJtuJM3dVtsMV9SY2',
      user_id_closed: 'xFqKTC9mMUMxJtuJM3dVtsMV9SY2',
      status: 'closed',
      comentario_ack: 'Serviço reiniciado com sucesso',
      comentario_closed: 'Serviço reiniciado com sucesso',
      created_at: '2025-10-22 14:10',
      ack_at: '2025-10-22 14:15',
      closed_at: '2025-10-22 14:45',
      logs: [
        { id: 'log-0012', incidente_id: 'inc-0008', time: '2025-10-22 14:10', message: 'Incidente criado' },
        { id: 'log-0013', incidente_id: 'inc-0008', time: '2025-10-22 14:15', message: 'Incidente reconhecido' },
        { id: 'log-0014', incidente_id: 'inc-0008', time: '2025-10-22 14:45', message: 'Incidente fechado' }
      ],
    },
    {
      id: 'inc-0009',
      user_escalado: 'fbMaxkasRefAgVxeSuxeTJIF5AS2',
      regra_id: '1a2b3c4d-0009',
      user_id_ack: 'mniYEzNopmPB08XkK5jDuTeANro1',
      user_id_closed: 'mniYEzNopmPB08XkK5jDuTeANro1',
      status: 'closed',
      comentario_ack: 'Problema resolvido após reinício do serviço',
      comentario_closed: 'Problema resolvido após reinício do serviço',
      created_at: '2025-10-22 15:00',
      ack_at: '2025-10-22 15:05',
      closed_at: '2025-10-22 15:30',
      logs: [
        { id: 'log-0015', incidente_id: 'inc-0009', time: '2025-10-22 15:00', message: 'Incidente criado' },
        { id: 'log-0016', incidente_id: 'inc-0009', time: '2025-10-22 15:05', message: 'Incidente reconhecido' },
        { id: 'log-0017', incidente_id: 'inc-0009', time: '2025-10-22 15:30', message: 'Incidente fechado' }
      ],
    },
    {
      id: 'inc-0010',
      user_escalado: 'xFqKTC9mMUMxJtuJM3dVtsMV9SY2',
      regra_id: '1a2b3c4d-0010',
      user_id_ack: '',
      user_id_closed: '',
      status: 'open',
      comentario_ack: '',
      comentario_closed: '',
      created_at: '2025-10-23 12:00',
      ack_at: '',
      closed_at: '',
      logs: [
        { id: 'log-0018', incidente_id: 'inc-0010', time: '2025-10-23 12:00', message: 'Incidente criado' }
      ],
    },
  ];

  const logsMock = [
    // 🔔 Notificações
    {
      id: 'log-001',
      type: 'notificacao',
      result: 'Notificação enviada para João (alerta de incidente crítico)',
      run_time: '2025-10-28T01:05:00',
      error: null,
      duration: 0.8,
    },
    {
      id: 'log-002',
      type: 'notificacao',
      result: 'Notificação enviada para Maria (alerta de manutenção programada)',
      run_time: '2025-10-28T01:06:00',
      error: null,
      duration: 1.1,
    },

    // ⚙️ Regras — Execuções
    {
      id: 'log-003',
      type: 'regra',
      result: 'Execução da regra de backup concluída com sucesso',
      run_time: '2025-10-28T01:12:00',
      error: null,
      duration: 3.5,
    },
    {
      id: 'log-004',
      type: 'regra',
      result: 'Erro ao executar regra de integridade (timeout excedido)',
      run_time: '2025-10-28T01:17:00',
      error: 'TimeoutError: operação excedeu o tempo limite',
      duration: 5.2,
    },

    // 🧭 Rotas — Mudanças (CRUD)
    {
      id: 'log-005',
      type: 'rota',
      result: 'Nova rota criada para user_id=12 (canal: Slack) | Período: 2025-10-25 08:00 → 2025-10-25 20:00',
      run_time: '2025-10-28T01:20:00',
      error: null,
      duration: 0.4,
    },
    {
      id: 'log-006',
      type: 'rota',
      result: 'Rota atualizada para user_id=8 (canal: Email) | Novo término: 2025-10-27 22:00',
      run_time: '2025-10-28T01:22:00',
      error: null,
      duration: 0.6,
    },
    {
      id: 'log-007',
      type: 'rota',
      result: 'Rota removida para user_id=5 (canal: SMS)',
      run_time: '2025-10-28T01:25:00',
      error: null,
      duration: 0.3,
    },
  ];


  const runnersMock = [
    { id: 'run-0001', ativo: 'active' , regra_id: '1a2b3c4d-0005'},
    { id: 'run-0002', ativo: 'inactive', regra_id: '1a2b3c4d-0002'},
    { id: 'run-0003', ativo: 'active', regra_id: '1a2b3c4d-0001'},
    { id: 'run-0004', ativo: 'inactive', regra_id: '1a2b3c4d-0003'},
    { id: 'run-0005', ativo: 'active', regra_id: '1a2b3c4d-0004'},
    { id: 'run-0006', ativo: 'inactive', regra_id: '1a2b3c4d-0006'},
    { id: 'run-0007', ativo: 'active', regra_id: '1a2b3c4d-0007'},
    { id: 'run-0008', ativo: 'inactive', regra_id: '1a2b3c4d-0008'},
    { id: 'run-0009', ativo: 'active', regra_id: '1a2b3c4d-0009'},
    { id: 'run-0010', ativo: 'inactive', regra_id: '1a2b3c4d-0010'},
  ];

  localStorage.setItem('regras', JSON.stringify(regrasMock))
  localStorage.setItem('incidentes', JSON.stringify(incidentesMock))
  localStorage.setItem('logs', JSON.stringify(logsMock))
  localStorage.setItem('runners', JSON.stringify(runnersMock))
}
